use_frameworks!

platform :ios, '8.0'

target 'WYLib_Example' do
  pod 'WYLib', :path => '../'

  target 'WYLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
